### ISSUE TITLE
exited with code 1

### ISSUE THREAD

**Issue by torres3490** [rnagabhyrava/plex-playlist-sync#12]
All Spotify playlist are followed and added to profile and I receive this error

exited with code 1
playlistSync  | INFO:root:Starting playlist sync
playlistSync  | INFO:root:Starting spotify playlist sync
playlistSync  | Traceback (most recent call last):
playlistSync  |   File "/app/usage.py", line 73, in <module>
playlistSync  |     track_names, poster_url = get_sp_track_names(
playlistSync  |   File "/app/helper.py", line 82, in get_sp_track_names
playlistSync  |     trackNames.append(track['track']['name'])
playlistSync  | TypeError: 'NoneType' object is not subscriptable

**Comment by rnagabhyrava** [comment]
Need more info to reproduce the issue

* What playlist caused this error?
* What image were you using latest/develop? Have you tried recreating the container to pull latest image?
* Do you have any songs from the playlist on your server?
* Any other info that can help reproduce the issue

-R

**Comment by torres3490** [comment]
> Need more info to reproduce the issue
> 
> * What playlist caused this error?
> * What image were you using latest/develop? Have you tried recreating the container to pull latest image?
> * Do you have any songs from the playlist on your server?
> * Any other info that can help reproduce the issue
> 
> -R

Baila Reggaeton

https://open.spotify.com/playlist/37i9dQZF1DWY7IeIP1cdjF?si=Fs00_Y4LTcuJJ42RakU0Kg&utm_source=copy-link

Is one and Rap Caviar

https://open.spotify.com/playlist/37i9dQZF1DX0XUsuxWHRQd?si=89sliJs7TZGL3KLh_-wMDw&utm_source=copy-link

**Comment by rnagabhyrava** [comment]
I tried both of the playlists above with the latest image. I was not able to reproduce the issue. Please make sure you're using the latest image or try the develop tag.
