### ISSUE TITLE
[Feature Request] Add option to sync or update playlist

### ISSUE THREAD

**Issue by hbooo** [rnagabhyrava/plex-playlist-sync#16]
For daily updated playlists it could be great to have the possibility to choose between : 

- sync (local playlist will be a copy of current spotify/deezer playlist)
- update (items in current spotify/deezer playlist will be added to existing items in local playlist)

**Comment by rnagabhyrava** [comment]
Does that mean update will keep all the old songs in the playlist that are not in the playlist anymore?

**Comment by hbooo** [comment]
Yes it's the behaviour i'm expected

**Comment by rnagabhyrava** [comment]
Added in 2016c17b57fb2f8280b4eeadbd0f4c2fa5776e43

**Comment by rnagabhyrava** [comment]
Implemented this in 2016c17b57fb2f8280b4eeadbd0f4c2fa5776e43

**Comment by hbooo** [comment]
> 

Nice, how Can I use it?

**Comment by rnagabhyrava** [comment]
Well, just re-read your initial post. The current implementation (check code-refactor branch, docker image tag:develop) updates the playlist without deleting but will remove any songs not in playlist anymore. Basically same as existing implementation but without deleting. I'll add an option to add stuff without removing songs that don't exist in spotify/deezer playlist anymore.

**Comment by rnagabhyrava** [comment]
Added this feature. Use the new variables from docker-compose attached and pull "develop" tag instead of "latest". Let me know how it goes

https://github.com/rnagabhyrava/plex-playlist-sync/blob/code-refactor/docker-compose-example.yml
