### ISSUE TITLE
Failing when tracks or posters no longer exists in playlists

### ISSUE THREAD

**Issue by home1800** [rnagabhyrava/plex-playlist-sync#30]
Using docker on ubuntu server 22.04 vm

```
INFO:root:Starting playlist sync
INFO:root:Starting Spotify playlist sync
ERROR:root:Spotify User ID Error
Traceback (most recent call last):
  File "/app/./plex-playlist-sync/run.py", line 71, in <module>
    spotify_playlist_sync(sp, plex, userInputs)
  File "/app/plex-playlist-sync/utils/spotify.py", line 88, in spotify_playlist_sync
    tracks = _get_sp_tracks_from_playlist(
  File "/app/plex-playlist-sync/utils/spotify.py", line 64, in _get_sp_tracks_from_playlist
    tracks = list(map(extract_sp_track_metadata, sp_playlist_tracks["items"]))
  File "/app/plex-playlist-sync/utils/spotify.py", line 58, in extract_sp_track_metadata
    url = track["track"]["external_urls"]["spotify"]
KeyError: 'spotify'
```

works in https://github.com/bassrock/spotify-plex-playlists, but that hasn't been updated in a couple of years.

No clue what I'm looking at.

**Comment by home1800** [comment]
I've gathered that much, but I got the username/ID from 
https://www.spotify.com/us/account/overview/ like specified in your instructions

![image](https://user-images.githubusercontent.com/69302307/179034466-5352fc82-953c-41bc-b27b-ded59d089615.png)

are there any other IDs to get? I've also tried setting up new spotify client ID/secrets

**Comment by rnagabhyrava** [comment]
Do you happen to have space in the beginning or at the end?

**Comment by rnagabhyrava** [comment]
Can you ping me on discord nota#3054 so I can help you better?

**Comment by rnagabhyrava** [comment]
Example: This playlist has a few songs not available in plex anymore https://open.spotify.com/playlist/7uAlOOCdhKP6pgLzQMI4gx

When try to use this to sync, code throws error as track url doesn't exist anymore.

Same with playlists where all tracks are missing, here poster will no longer exists unless user manually added one.
