### ISSUE TITLE
Multiple user support

### ISSUE THREAD

**Issue by fwicht** [rnagabhyrava/plex-playlist-sync#41]
It'd be great to support a list of comma separated user ids.

**Comment by rnagabhyrava** [comment]
Do you mean support for multiple spotify/deezer user id's or plex users? If it's the later, it's not possible with current plex api limitations (at least last when I checked).

**Comment by anatosun** [comment]
I meant both: imagine your friend/family wanting to sync their playlists to their own personal plex user.

**Comment by rnagabhyrava** [comment]
Refer to my notes in #14 

+ A possible workaround is to use the new plexamp playlist grant access feature [Link here](https://www.reddit.com/r/PleX/comments/wdu426/plexamp_v430_released/)

**Comment by anatosun** [comment]
Ok I see the issue at hand here. To me, it seems that sharing playlists from one user is a bit of a hack. Are we sure that we cannot handle multiple plex client authenticated with different users?

**Comment by rnagabhyrava** [comment]
From plex api i don't see anything other than playlist.copyToUser that will help with this. Sorry I haven't found anything yet if you find anything let me know. I am happy to implement.

**Comment by rnagabhyrava** [comment]
Duplicate of #14 . Please continue discussion in #14
