### ISSUE TITLE
Instead of writting missing songs as a csv, request in Lidarr

### ISSUE THREAD

**Issue by vodobaas1** [rnagabhyrava/plex-playlist-sync#47]
As the title states it would be awesome if when plex-playlist-sync finds a missing song, it would tell lidarr.

**Comment by rnagabhyrava** [comment]
As far as I know lidarr does not support single tracks and it is out of scope for this project. Sorry.

**Comment by trevren11** [comment]
It doesn't support single tracks, but this wouldn't be too hard to do the albums, I might try to take a stab at it at some point

**Comment by noworthwhile** [comment]
Would love to see this as well :)
