### ISSUE TITLE
How does it search Plex for the song? 

### ISSUE THREAD

**Issue by dustiebin** [rnagabhyrava/plex-playlist-sync#52]
Hi, not sure if this is a bug or request... so put it as a request. 

How does this playlist creator find the music on my plex server?

This is the first time I have used this docker.
On a recent playlist imported from Spotify, I looked at the CSV file created for the tracks not found.
On checking a few of them I do have them on my server but not in the Album Spotify has them in, mine are in Compilation albums. 

So does your script look up Song Name, Artist and Album? 
If so can it then search just on Song Name and Artist as a fall back to see if it is anywhere else on the Plex server? 

An example from the logs:
INFO:root:retrying search for Lovefool - Radio Edit
INFO:root:search for Lovefool - Radio Edit successful

But this did not go into the playlist on Plex, but when I search for Lovefool I have the song twice, once by Just Jack (live lounge) and the other by The Cardigans

When it says successful, does that mean it was successfully added to the CSV file or the playlist? 

Thanks

**Comment by rnagabhyrava** [comment]
It search plex with the track title. Then pick the result with artist name similarity or album name similarity>0.9. I know what you're talking about the mismatch in album names between plex and spotify/deezer. I don't know a better way to deal with that.

https://github.com/rnagabhyrava/plex-playlist-sync/blob/c3333a506066c1294f67f297681fd2c342b4e2ff/plex-playlist-sync/utils/plex.py#L81

**Comment by dustiebin** [comment]
wow, thanks for the quick response!

something from my playlist messed it up then, 

Got one for Pearl Jam - Alive
not on the same album as Spotify but on greatest hits ... 

Not to worry, the CSV is great so can check them off and add them if I have them

**Comment by dustiebin** [comment]
thanks for the work on this, saved me a heck of a time getting a playlist together for New Year!

**Comment by rnagabhyrava** [comment]
Glad to help!

**Comment by jackmawer** [comment]
Just to say I'm also having occasional issues where songs by the correct artist and with a similar or the same song title sometimes don't seem to be added correctly if they are in a different album to Spotify. I'm not sure what the fix could be but I imagine other users will run into similar issues so it might be worth considering.
