### ISSUE TITLE
 CSV files not deleted when all media exists in Plex

### ISSUE THREAD

**Issue by Drag-3** [rnagabhyrava/plex-playlist-sync#59]
**Description:**
 When all media files in a playlist exist in Plex, the associated CSV file is not deleted and the following message is displayed: "`playlistSync | INFO:root:Failed to delete --csv--, likely permission issue`". 

**Configuration**
The Docker container is on Windows via docker-desktop (WSL2) with the mount being local to the computer. 
The Plex server is on a separate computer running Linux Mint and the media files are on a NAS.

**Steps to Reproduce:**

    1. Run the Docker container and observe the logs.
    2. Create a playlist with media files that exist in Plex.
    3. Check if the associated CSV file is deleted.
    4. If the CSV file is not deleted, check if the message "playlistSync | INFO:root:Failed to delete --csv--, likely permission issue" is displayed.

**Expected behavior:**
When all media files in a playlist exist in Plex, the associated CSV file should be deleted automatically.

**Screenshots:**
![image](https://user-images.githubusercontent.com/67492100/235576170-0bf6c8ce-d463-4c10-b54e-61f5588115b6.png)

**Additional Information:**
If the issue is related to my docker-compose configuration or some Windows setting, let me know.

**Comment by rnagabhyrava** [comment]
Sorry for the late response. It is most likely a permission issue try giving the folder's read write modify access to the user and try again.
