### ISSUE TITLE
not all public playlists are synced

### ISSUE THREAD

**Issue by KeenMaron** [rnagabhyrava/plex-playlist-sync#64]
Hi,

I love Plex Playlist Sync; it makes it so much easier to automate getting updated playlists in Plex.

However, I've encountered an issue:
All my playlists are set to public, but only a part of them is being synced. Why is that?

**Comment by rnagabhyrava** [comment]
Your playlists MUST be public and added to your profile. Check the video
attached.


https://m.youtube.com/watch?v=kiWpFpYQfnA

**Comment by KeenMaron** [comment]
Ok found the solution:
"Check if you've added the playlist to your profile. In general a public playlist means that anyone with the link can view it, however, it won't show up on your profile unless you manually add it. You can do that from the three dots menu > Add to profile."
