### ISSUE TITLE
Manually added songs in existing playlist got removed after next sync

### ISSUE THREAD

**Issue by KeenMaron** [rnagabhyrava/plex-playlist-sync#65]
Hi,

I want to manually add songs to my Plex playlist that aren't being detected correctly by the script. 

My problem is that when I start the script again after a while to update the playlists, the manually added songs disappear. Why is this happening? I tought it updates existing playlist and does not delete them if they already exists? 

Could you please let me know which part of the code is responsible for this behavior, and perhaps I can make the necessary changes in my local branch.

**Comment by KeenMaron** [comment]
"APPEND_INSTEAD_OF_SYNC=0 # Default 0, 1 = Sync tracks, 0 = Append only"

thought 0 is to "add" new songs only. But it is 1 not 0. Maybe i have a missunderstandig of the settings.
Set it to 1 it only adds new songs and does not delete the previous playlist content.

**Comment by rnagabhyrava** [comment]
You're right about APPEND_INSTEAD_OF_SYNC but keep in mind that this will never remove any songs from the playlist.
