### ISSUE TITLE
ERROR:root:Missing Plex Authorization Variables

### ISSUE THREAD

**Issue by IrishMarty10** [rnagabhyrava/plex-playlist-sync#67]
Every time I try to run the pulled image I get this error. Any idea how to fix it. I am not well-versed on programming.

1. Configuration: Docker Desktop Windows 11. Running latest plexplaylistsync image pulled from the hub.
2. Playlist(s) causing the issue:
3. Song(s) causing the issue:

**Screenshots**
![Screenshot (65)](https://github.com/rnagabhyrava/plex-playlist-sync/assets/147451755/40cbc070-5a28-400a-a19a-f1df8a55e74e)

**Additional context**

**Comment by rnagabhyrava** [comment]
Please read the readme file for configuration settings. There are environment variables that needs to be passed. I recommend using the docker compose method. Windows docker runs with wsl2 if i am not wrong you can use compose file from wsl.

**Comment by IrishMarty10** [comment]
Does it require a premium subscription to either Spotify or Plex? Also, do I need to individually set up spotipy and plexapi services? Still having issues having followed all the steps.

**Comment by rnagabhyrava** [comment]
It does not require either plex or spotify subscriptions. You don't need to individually setup spotipy/plexapi they're part of the docker container. But you need to have a plex server running and accessible to this program please refer to prerequisites section of the readme on how to get the api keys for plex and Spotify. 

https://github.com/rnagabhyrava/plex-playlist-sync#prerequisites

**Comment by IrishMarty10** [comment]
Finally got it working. I'd missed the port number off the end of my Plex URL in the yml file. Thought I was going mad.

**Comment by rnagabhyrava** [comment]
Glad it worked out. Have fun!
