### ISSUE TITLE
[BUG] Syncing the wrong songs to playlist

### ISSUE THREAD

**Issue by calvin-li-developer** [rnagabhyrava/plex-playlist-sync#70]
**Describe the bug**
I have this bug where when syncing my Top 100 songs for 2023. It puts in songs that has the same name but completely different artist

**To Reproduce**
1. use playlist link ****redacted****
2. use tool to sync
3. For custom order track 43 Not OK by Robert Grace. I get in Plex Not Ok by Kygo

Can try this song in your playlist to test but I think there are more songs that happens to this bug happening just dont have an exhaustive list.

**Expected behavior**
Having Not OK by Robert Grace in Playlist. btw, I do have the song in my plex.

**Screenshots**
on Spotify:
![image](https://github.com/rnagabhyrava/plex-playlist-sync/assets/65045619/f44e6df1-7b1f-4a9d-9a16-13989e35b485)

on Plex:
![image](https://github.com/rnagabhyrava/plex-playlist-sync/assets/65045619/d3038f95-21f9-4f97-a26b-7c6d765f7b0b)

**Additional context**

**Comment by rnagabhyrava** [comment]
The project uses sequenceSimilarity which can generate false positives for foreign names and names that are shorter. Sorry not sure if I can help with that. 


https://github.com/rnagabhyrava/plex-playlist-sync/blob/c3333a506066c1294f67f297681fd2c342b4e2ff/plex-playlist-sync/utils/plex.py#L83
