### ISSUE TITLE
Spotify sync error

### ISSUE THREAD

**Issue by torres3490** [rnagabhyrava/plex-playlist-sync#9]
I follow a bunch of Spotify playlist , the playlist are public but they don't sync , I receive this error

- Network plexplaylistspotifysync_default  Created                                                                0.0s
 - Container playlistSync                   Created                                                                0.1s
Attaching to playlistSync
playlistSync  | INFO:root:Starting playlist sync
playlistSync  | INFO:root:Starting spotify playlist sync
playlistSync  | Traceback (most recent call last):
playlistSync  |   File "/app/usage.py", line 73, in <module>
playlistSync  |     track_names, poster_url = get_sp_track_names(
playlistSync  |   File "/app/helper.py", line 81, in get_sp_track_names
playlistSync  |     trackNames.append(track['track']['name'])
playlistSync  | TypeError: 'NoneType' object is not subscriptable

**Comment by mynvnow** [comment]
Thanks for the issue. Can you share the playlist that caused the issue? You can contact me on discord nota#3054

**Comment by rnagabhyrava** [comment]
Thanks for the issue. Can you attach the playlist that's causing the issue? DM on discord is fine as well nota#3054

**Comment by torres3490** [comment]
> Thanks for the issue. Can you attach the playlist that's causing the issue? DM on discord is fine as well nota#3054

What's your DM on Discord?

**Comment by torres3490** [comment]
This is the playlist

https://open.spotify.com/playlist/37i9dQZF1DWW4igXXl2Qkp?si=7HHH3qGZRoWndjBXMiYrbw&utm_source=copy-link

**Comment by rnagabhyrava** [comment]
Thanks for sending the playlist. I noticed that the issue occurs when there is no playlist created (because no song available locally) but the posters process is still looking to create posters. I deployed a fix and pushed a new image. Try to pull the image and let me know how it goes. Thanks ✌️

**Comment by torres3490** [comment]
> 

posters are working, hopefully one day you can fix it to sync with all playlist and not just user created. great job on the script and thanks for the quick reply

**Comment by rnagabhyrava** [comment]
The script pulls all of the public playlists in user's profile [refer to this link on how to add a playlist to profile](https://allthings.how/how-to-add-playlists-to-your-spotify-profile/) for some reason the number of playlists you can add to your profile is limited to 4 on web. You can use mobile app to add more to your profile.

**Comment by rnagabhyrava** [comment]
This issue was addressed and new image with fix was deployed.
